### ISSUE TITLE
Is there any way I could overwrite the text size for atom-rails-model-schema?

### ISSUE THREAD

**Issue by edyywang** [platanus/atom-rails-model-schema#3]
This is a great tool. (y)
However sometimes the sidebar is just too big (over 1/3 of my 13" screen) due to long field name.
How could I resize it by overwrite the text size in my atom stylesheet?
Or another way I could resize the schema bar
Thanks!

**Comment by juliogarciag** [comment]
You can set styles for element inside `.rails-model-schema` as they are in the stylesheet: https://github.com/platanus/atom-rails-model-schema/blob/master/styles/rails-model-schema.less. You can change the css whatever you want. Anyway, i have the following solutions in mind:

1. Make the right panel resizable: I'm currently just using `atom.workspace.addRightPanel`[https://atom.io/docs/api/v1.0.11/Workspace#instance-addRightPanel] and i found that [this](https://github.com/atom/atom/issues/3680) can help. Have to research a bit thought because the api documentation doesn't show a `resizable` option as this issue does.
2. Set some styles to make it more usable: Maybe a `max-width: 20%` or a combination of various styles.
3. Make the field names to only show a part of the name if the name is too big. So, if the name has more than 20 characters (or any number), we could show "thisisthenamefieldan..." and if the user hover the mouse, show the entire name: "thisisthenamefieldanisalargename". When copying the file via click in the name, the full name should be copied.

I will check out a good solution amoung those listed here later this week.

**Comment by edyywang** [comment]
Thanks. After setting font-size: 0.8em, it looks much better now (y)
