### ISSUE TITLE
display schema for inherited model

### ISSUE THREAD

**Issue by audy** [platanus/atom-rails-model-schema#4]
Nice plugin!

I'm using single-table inheritance in an app and noticed that rails-model-schema doesn't show the schema for the model's parent.

For example,

```ruby
# app/models/user.rb
class User < ActiveRecord::Base
end

# app/models/admin.rb
class Admin < User
end
```

I don't know if this is intentional or not. Just thought I would point it out.

**Comment by juliogarciag** [comment]
[Here](https://github.com/platanus/atom-rails-model-schema#current-drawbacks) i explain why. This is intentional because i didn't know how to fix it without running the RoR runtime. The code is just parsing the `schema.rb` file. Currently, i think i could have a solution: to read the superclass of the class too and use that to lookup for the table if the class name was not enough. Maybe the friday i will have that fix applied.

**Comment by juliogarciag** [comment]
Well. It's working now. Try updating the package to (at least) the 0.5.0 version.

**Comment by audy** [comment]
Awesome. Thanks!
